"""empty message

Revision ID: 732c269683d1
Revises: 6f6610d2518e
Create Date: 2022-08-12 11:38:25.415221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732c269683d1'
down_revision = '6f6610d2518e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'test')
    # ### end Alembic commands ###
